### ISSUE TITLE
Need to go back when labeling data

### ISSUE THREAD

**Issue by AbeHandler** [datamade/parserator#12]
I am labeling data now with parserator. Sometimes I hit the wrong key and want to undo. I don't see a way to do that with the labeler. Would be great to add this feature or make the command line option more obvious.

` What is 'of' ?
` 5
` What is 'notless' ?
` 5
` What is 'than' ?   #should have pressed 7... not five...
` 5
` What is '$100,000.00' ?

**Comment by cathydeng** [comment]
definitely a good idea - I've run into the same thing when labeling & it's tedious to fix. I'll work on making the console labeling more user friendly

**Comment by AbeHandler** [comment]
Cool. Thanks. While we're at it, it would be helpful if you could reprint the numbers from the console for every new item to label. I often forget the meaning of the numbers and have to scroll up. 

Start console labeling!

These are the tags available for labeling:
0 : amendment_amount
1 : amendment_amount_description
2 : agreement_amount
3 : agreement_amount_description
4 : other_amount
5 : other_amount_description
6 : document_self_reference
7 : amount_alphabetic
8 : skip

**Comment by cathydeng** [comment]
just fixed this in parserator 0.3.4. you can now type 'oops' to re-label a string
