### ISSUE TITLE
UI suggestion

### ISSUE THREAD

**Issue by AbeHandler** [datamade/parserator#13]
In training data, it would be helpful if you could reprint the numbers from the console for every new item that needs to be labeled. I often forget the meaning of the numbers when I am 10 or 20 items deep into the labeling... 

So like this could be reprinted each time:

Start console labeling!

These are the tags available for labeling:
0 : amendment_amount
1 : amendment_amount_description
2 : agreement_amount
3 : agreement_amount_description
4 : other_amount
5 : other_amount_description
6 : document_self_reference
7 : amount_alphabetic
8 : skip

**Comment by cathydeng** [comment]
if you type 'help' it'll print the labels again. that's not clear though b/c it only prompts you to type 'help' if you type something invalid - I'll add better text

**Comment by AbeHandler** [comment]
How about something like: 

Is this correct? (y)es / (n)o / (s)kip / (f)inish tagging / (l) reprint labels?

**Comment by cathydeng** [comment]
alrighty, just updated the console labeling. in parserator 0.3.4, the string label prompt is now ``Is this correct? (y)es / (n)o / (s)kip / (f)inish tagging / (h)elp``
