### ISSUE TITLE
Parserator train command should take a glob

### ISSUE THREAD

**Issue by AbeHandler** [datamade/parserator#17]
I am training parserator on lots of XML files (one XML file for each document cloud id). It would be nice if parserator could train on a glob of xml files (at least I would want this feature). 

So like: 

    parserator train *.xml contract_parser

Thoughts?

**Comment by fgregg** [comment]
Sounds like a good idea.

**Comment by cathydeng** [comment]
hey @AbeHandler - in parserator 0.3.6, you can now run

```parserator train "path/to/traindata/*.xml" contract_parser```

the glob pattern has to be quoted, since the shell auto-expands it otherwise & I didn't wana mess w/ the order of the parserator arguments. thx for the idea!

**Comment by AbeHandler** [comment]
works great. Thanks!
