### ISSUE TITLE
review documentation w/ fresh eyeballs

### ISSUE THREAD

**Issue by cathydeng** [datamade/parserator#2]

**Comment by derekeder** [comment]
@cathydeng overall, looks good. perhaps we should add a section on how to use the parser once its been created?

**Comment by cathydeng** [comment]
@AbeHandler would love any feedback you have while working through this, if anything in the documentation is unclear

**Comment by AbeHandler** [comment]
Sure thing. I will keep an eye out. @fgregg gave me a hands on tutorial at NICAR -- so I've mostly skipped the docs.

**Comment by chengguangnan** [comment]
Hi @cathydeng, I want to know, when you re-train the model, do you only need to feed the new input data or you have to feed all the data again?

Also, how many does it take to train the model? On usaddress, it takes at least 30 minutes already to run: `parserator train training/'*'.xml usaddress`, I'm not sure how much longer should I wait.

Those two questions are better to be answered in the doc.

**Comment by cathydeng** [comment]
hey @chengguangnan - sorry for the late response!

the train command creates a model from the training files you specify, and doesn't remember anything about previous models. so, you should feed all the data.

training should only take a few seconds, definitely under a minute. how many strings do you have in your training data?

these bits of info definitely belong in the docs, thanks for the input
