### ISSUE TITLE
-bash: parserator: command not found

### ISSUE THREAD

**Issue by mashcode** [datamade/parserator#20]
Running 'parserator init landmarks' generates this error

'parserator: command not found'

I used 'pip install --user parserator'

**Comment by cathydeng** [comment]
this isn't a parserator issue - command not found means that either parserator didn't install, or it installed somewhere outside of your python search path.

do you see parserator when you run ```pip list```? did you try ```pip install parserator```?

**Comment by mashcode** [comment]
Yes it's in the pip list. 'pip install parserator' fails. Permissions.

**Comment by cathydeng** [comment]
ok, my hunch is that wherever you installed parserator is not in your search path (what you see w/ ```echo $PATH```), in which case you'd have to modify your $PATH variable

**Comment by mashcode** [comment]
Hi Kathy, since I prefer avoiding sudo I applied the --user option which installed it here: /Users/marc/Library/Python/2.7/lib/python/site-packages
Adding this path to bash does nothing.

All other python packages are installed here: /Library/Python/2.7/site-packages

Is there a config file I can add to my local project to satisfy the package path?

**Comment by mashcode** [comment]
ok, I blew away the local user parserator package and sudo'd it into /Library/Python/2.7/site-packages

thanks for your kind attention

closing
