### ISSUE TITLE
Labeller incompatible with Python 3

### ISSUE THREAD

**Issue by wfdd** [datamade/parserator#25]
* The `label` function in `manual_labeling` expects the input to be Unicode-encoded, but Python 3 `open` defaults to Unicode.
* `data_prep_util`'s `appendListToXMLfile` doesn't specify a write mode (thus defaulting to Unicode), while `etree.tostring` produces a bytes string.
* `etree.tostring` will have XML-escaped Unicode characters, so decoding its output in [`test_manual_labeling`](https://github.com/datamade/parserator/blob/master/tests/test_manual_labeling.py) accomplishes nothing.

**Comment by chengguangnan** [comment]
yeah, having the same issue
