### ISSUE TITLE
Training on usaddress and probable twice on same dataset

### ISSUE THREAD

**Issue by renospec** [datamade/parserator#36]
Is there a way to train on parserator with usaddress and probablepeople with one training session to avoid having two sessions? This is time consuming to retrain twice on each text string.
One session training on usaddress and another training session on probablepeople....!
Here is some text to consider.....

TRUST CA073108132 EXHIBIT "A" IDENTIFICATION OF PROPERTY OWNERS AND PROPERTY DESCRIPTION Record Owner(s) Names: FOLEY JONES FAMILY TRUST; Trustee(s): Patricia Jones, Henry Foley Address: 12349 Oliva Rd, San Diego, CA 92128

**Comment by fgregg** [comment]
Yes, you could write code to do this. This is not something we are going to implement at this time (or would want in the library).
