### ISSUE TITLE
Can we extend this to other countries with right labelled data

### ISSUE THREAD

**Issue by ishaan007** [datamade/parserator#37]
Is this python API customized for US addresses only?,or can we give the model, training data of other countries with english addresses(through this process https://github.com/datamade/usaddress/tree/master/training) and It still might work ?

**Comment by fgregg** [comment]
Yes, absolutely.

**Comment by jeancochrane** [comment]
Let us know if you get a parser working for non-US addresses, @ishaan007! We'd love to see your work. For now, I'm going to close this issue since it seems like your question has been answered.
