### ISSUE TITLE
parserator's us_address succesfully trained .crfsuite file not being used and also not found in the directories

### ISSUE THREAD

**Issue by pavanAlluri** [datamade/parserator#39]
Labelling and training of parserator for usaddress has been successful. Once trained, the resulting .crfsuite file is supposedly & said to be saved at ...workingdirectory/usaddress/usaddress.crfsuite

But no such file is found. In fact no such folder exists in that directory. Also tried parsing after training, assuming if it is saved in some other location and only i couldn't see it. But the parsing after training is default parsing and not according to the trained file ( i can tell because i am testing on the same trained file and i am getting different results.)

[https://github.com/datamade/parserator/issues/3](url)
i have looked into this issue but in my case, am not finding the file nor getting results as per training.

Kindly advise on how to proceed?

**Comment by jeancochrane** [comment]
Hey @pavanAlluri,

Are you only using parserator for usaddress? If so, you might have more success developing with [the usaddress library.](https://github.com/datamade/usaddress) I haven't had a moment to try to recreate your issue yet, but from first glance it sounds like you're describing the directory structure of usaddress and not parserator.

**Comment by pavanAlluri** [comment]
Hi @jeancochrane,
I am using probablepeople and usaddess to train for both name & address extraction. 
since usaddress is working as it should be and parserator is displaying as saving the training file but it isn't, i assume this to be a problem with parserator. 

I will look into the development with usaddress, but do let me know if for there is something i am overlooking for this issue to arise?

Thank you.

**Comment by pavanAlluri** [comment]
Hi @jeancochrane,
solely running with usaddress worked with development link. Thank you

**Comment by jeancochrane** [comment]
Great to hear!
