### ISSUE TITLE
Training parserator with names in text/Problem with variations of name formats

### ISSUE THREAD

**Issue by renospec** [datamade/parserator#40]
Hi
Finished training with data that has name formats.
Now testing with different formats and  it  is failing due to non trained formats.
Is there a way go get past having to train all different permutations of name formats?
This will be very challenging for name parsing...
Help !

**Comment by renospec** [comment]
Perhaps Name parsing/Training is not a well embraced function of parserator.
I have tested Probable People and was hoping for better accuracy in training with Name formats in Parserator.

**Comment by jeancochrane** [comment]
Hey @renospec,

Thanks for waiting on this. Can you give me a better sense of what you're trying to do? If you're just looking to alter/improve the behavior of name parsing, you might find it easier to develop off of the probablepeople library and retrain the model yourself. We don't have probablepeople-specific docs for this yet, but the [guide for usaddress](https://github.com/datamade/usaddress/blob/master/training/README.md) should be nearly identical.

**Comment by renospec** [comment]
Thank You
I have developed with the ProbablePeople Library and have trained the model for my data.
After the training session, I started testing different name formats and found that name formats that were not trained for were not successfully parsed. So that means that I have to train all variations of name formats....!

**Comment by jeancochrane** [comment]
Thanks for your patience on this @renospec! It's been a busy week on my end.

When you were developing probablepeople, did you train it on the canonical training data in addition to your new data? As per the [Building & Testing the Code](https://github.com/datamade/probablepeople#building--testing-development-code) section of the docs, that command should look like this:

```
 parserator train name_data/labeled/labeled.xml,name_data/labeled/company_labeled.xml probablepeople
```

That's all I can think of off the top of my head that might be causing your error here. If you did that correctly, then the next step will be for me to take a look at your new training data and the name formats you're testing to see if I can reproduce your error. Are you comfortable sharing that data?
