### ISSUE TITLE
"Parserator init" The specified procedure could not be found

### ISSUE THREAD

**Issue by kriebb** [datamade/parserator#41]
Using Visual Studio 2017
Using Windows 10 64 bit

So I've run:

```
pip install parserator
Requirement already satisfied: parserator in c:\program files\python36\lib\site-packages
Requirement already satisfied: future>=0.14.3 in c:\program files\python36\lib\site-packages (from parserator)
Requirement already satisfied: python-crfsuite>=0.7 in c:\program files\python36\lib\site-packages (from parserator)
Requirement already satisfied: lxml>=3.7.3 in c:\program files\python36\lib\site-packages (from parserator)
Requirement already satisfied: backports.csv in c:\program files\python36\lib\site-packages (from parserator)

```
Then I've Run:

```
c:\users\kristof\documents\visual studio 2017\Projects\PythonApplication1\PythonApplication1>parserator init bankstatement
Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\Scripts\parserator.exe\__main__.py", line 5, in <module>
  File "c:\program files\python36\lib\site-packages\parserator\main.py", line 14, in <module>
    from . import manual_labeling
  File "c:\program files\python36\lib\site-packages\parserator\manual_labeling.py", line 9, in <module>
    from lxml import etree
ImportError: DLL load failed: The specified procedure could not be found.
```

What I am doing wrong to init this?

**Comment by jeancochrane** [comment]
Hm, very weird. We've had a few different problems with Visual Studio recently on our parserator derivatives. You may want to take a look at [this issue with Python 3.6](https://github.com/datamade/usaddress/issues/182) and [this issue with lxml](https://github.com/datamade/usaddress/issues/177).

What version of Python are you running? 3.6 on Visual Studio seems to be the common denominator for a lot of these issues.

**Comment by kriebb** [comment]
It is idd python 3.6 with VS 2017
```
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26430.15
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
```
python -v on the vs command prompt gives this:

`Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32`

I'll visit the links

**Comment by kriebb** [comment]
After visiting those links and getting nothing, I've uninstalled the python 3.6 using the visual studio installer. I've reinstalled it with python 2.7.13 . Now I got this:


```
C:\Python27amd64>parserator init testParser

Initializing directories for testParser <open file '<stderr>', mode 'w' at 0x000000000284B150>
* testParser <open file '<stderr>', mode 'w' at 0x000000000284B150>
* raw <open file '<stderr>', mode 'w' at 0x000000000284B150>
* training <open file '<stderr>', mode 'w' at 0x000000000284B150>
* tests <open file '<stderr>', mode 'w' at 0x000000000284B150>

Generating __init__.py <open file '<stderr>', mode 'w' at 0x000000000284B150>
* testParser/__init__.py

Generating setup.py
* setup.py <open file '<stderr>', mode 'w' at 0x000000000284B150>

Generating test file <open file '<stderr>', mode 'w' at 0x000000000284B150>
* tests/test_tokenizing.py <open file '<stderr>', mode 'w' at 0x000000000284B150>

C:\Python27amd64>
```

Now I got to find out, if it is a problem for me using python 2.7 instead of 3.6.

**Comment by jeancochrane** [comment]
Looks good! Keep us updated with how it goes.

**Comment by kriebb** [comment]
What is the way to give an update? I'm foreign to the language of python,
but that'll learn fast. However, i'm looking at the structure of you other
programs, and that is somewhat more difficult. I'll need to study it. I'm
want to see if I can see it working with bank statements, I can export from
my banking feed. That's normal text (no standards, csv, etc...), but I can
write the regex's myself. But if I can train a program to do it, it should
be more maintainable. That's why I want to achieve.



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=riebbels.kristof@gmail.com&idSignature=22>

Op ma 10 jul. 2017 om 17:02 schreef Jean Cochrane <notifications@github.com
