### ISSUE TITLE
Merge pull request from unicode rewrote training.py and borked a number of downstream projects

### ISSUE THREAD

**Issue by WildGunman** [datamade/parserator#46]
I'm not exactly sure what happened when #45 "unicode" was merged in, but it appears to have rewritten a lot of things. Notably, `training.py`, which now lacks the `readTrainingData` method. This breaks a number of packages which depend on the method, including the training and testing environments for **usaddress** and **probablepeople.**

It's possible the problem is limited to this one method, but it might be advisable for the maintainer to doublecheck the merge.

**Comment by fgregg** [comment]
Thanks for the report, this should all be fixed as of the https://pypi.python.org/pypi/parserator
